### ISSUE TITLE
panics when sorting files with names as big numbers

### ISSUE THREAD

**Issue by hey-adora** [pop-os/cosmic-files#258]
Panics on trying to sort files at `tab.rs` in `scan_path` function at line 315

```
thread 'tokio-runtime-worker' panicked at /home/hey/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lexical-sort-0.3.1/src/cmp.rs:106:21:
attempt to multiply with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_const::panic_const_mul_overflow
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:180:21
   3: lexical_sort::cmp::natural_lexical_cmp
   4: cosmic_files::tab::scan_path::{{closure}}
             at ./src/tab.rs:315:14
   5: alloc::slice::<impl [T]>::sort_by::{{closure}}
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/slice.rs:267:34
   6: core::slice::sort::merge
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/slice/sort.rs:963:28
   7: core::slice::sort::merge_sort
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/slice/sort.rs:1102:17
   8: alloc::slice::stable_sort
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/slice.rs:887:5
   9: alloc::slice::<impl [T]>::sort_by
   ```

![image](https://github.com/pop-os/cosmic-files/assets/146812294/681f0c5a-a90e-4a16-817c-0194eaa96e97)

looks like the bug is in the lexical-sort repo
but it seems the fix is not being merged for a year now
https://github.com/Aloso/lexical-sort/pull/11

**Comment by joshuamegnauth54** [comment]
It seems the crate is currently unmaintained according to the readme. The author recommends [icu_collator](https://docs.rs/icu_collator/latest/icu_collator/) which is part of the larger (and well maintained) [icu4x](https://github.com/unicode-org/icu4x) project. `icu4x` is also an official Unicode Consortium project.

I'll see if I can replace `lexical-sort` with `icu_collator`.
