### ISSUE TITLE
Panic when operating on files in trash

### ISSUE THREAD

**Issue by qarmin** [pop-os/cosmic-files#508]
**Cosmic-files version:**
5e0ef57ef853953f1e201bdbd08c531e8743acd9

**Issue/Bug description:**
When trying to open some files in trash and later removing all files from it, I got this crash(app still works, so looks that only one thread crashed)

```
thread 'tokio-runtime-worker' panicked at /home/rafal/.cargo/git/checkouts/trash-rs-73fb3f8cbeeee6a0/483f839/src/freedesktop.rs:266:5:
assertion failed: virtually_exists(&file).map_err(|e| fs_error(&file, e))?
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2024-09-27T19:14:26Z WARN  cosmic_files::app] failed to rescan: task 89 panicked with message "assertion failed: virtually_exists(&file).map_err(|e| fs_error(&file, e))?
```
**Steps to reproduce:**
TODO - happened only once and cannot really reproduce it, but trying

**Comment by joshuamegnauth54** [comment]
Ping me if you're able to replicate it.

I may be able to fix it, but I don't want to modify either project unless I can test my code.

**Comment by elec-n3m** [comment]
Similar issue happens when you try to move multiple files at once into trash.  I am not sure if this would be under the same issue or not but here is what I have.

`thread 'main' panicked at /build/cosmic-files-Fv5Ho2/cosmic-files-0.1.0~1730945036~24.04~93470fa/vendor/trash/src/freedesktop.rs:145:42:
called `Option::unwrap()` on a `None` value
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2024-11-09T16:53:16Z WARN  cosmic_files::app] trash needs to be rescanned but sending message failed: SendError { kind: Disconnected }`

**Comment by rouffy-dawg** [comment]
I am not sure if this is entirely related but i am able to replicate this panic. If there are some files in the trash 
`~/.local/share/Trash/` usually you will have two folders in there, one called `files` and one called `info`. If you were to delete files from `~/.local/share/Trash/files/` and try to access the Trash folder through the cosmic files app it would crash and panic in a similar way with the resulting error 

```
thread 'tokio-runtime-worker' panicked at /home/<username here>/.local/share/cargo/git/checkouts/trash-rs-73fb3f8cbeeee6a0/483f839/src/freedesktop.rs:266:5:
assertion failed: virtually_exists(&file).map_err(|e| fs_error(&file, e))?
```
I looked a bit into where it crashes and managed to figured out that the left over metadata files in `~/.local/share/Trash/info/`  (at least from my guess) are confusing the `trash-rs` crate and when the function `trash::os_limited::list()` is called it falsely reports the amount of files in the trash so when it continues and tries to confirm the existence of the said files in the following function of the crate
```
assert!(virtually_exists(&file).map_err(|e| fs_error(&file, e))?);
``` 
it return an error and prompts the operation to panic.

**Comment by KodeBarista** [comment]
Has it been fixed?

**Comment by leviport** [comment]
I assume so. We can reopen if not.
